[GAF-1] Feature/db connection
LekiTech/GafalagParser pull request #5
Opened 2021-11-12 02:55 UTC by eskendarov

2021-11-12 05:23 UTC, tadzjibov commented on src/main/resources/database/db.properties
> +psql.password=password
В Dockerfile gafalag-api имя и пароль базы данных являются `docker` так что лучше и здесь их поставить

2021-11-15 03:46 UTC, tadzjibov requested changes

2021-11-15 03:46 UTC, tadzjibov commented on src/main/java/org/lekitech/gafalag/DBConnection.java
> +    private static final String QUERY_DELETE = "DELETE FROM lez_rus WHERE id = ?";
Для чего нужен этот класс с выписанными SQL запросами если можно использовать `session.save(<entityObject>)` как ты сделал это в методе `main` класса `App`?

2021-11-15 14:50 UTC, eskendarov commented on src/main/java/org/lekitech/gafalag/DBConnection.java
> +    private static final String QUERY_DELETE = "DELETE FROM lez_rus WHERE id = ?";
Класс DBConnection.java с низкоуровневыми запросами - экспериментальный, и он в принципе не нужен в проекте, так мы используем ORM. Удалить его?

2021-11-15 17:26 UTC, tadzjibov commented on src/main/java/org/lekitech/gafalag/DBConnection.java
> +    private static final String QUERY_DELETE = "DELETE FROM lez_rus WHERE id = ?";
Если он все еще нужен для тестов то поставь над декларацией класса аннотацию `@Deprecated`, а затем когда не нужен будем удалим

2021-12-31 16:14 UTC, tadzjibov approved these changes

2021-12-31 17:19 UTC, merged